disable:
   
   # Disable disguised players from picking up items
   item-pick-up: DISABLE_ITEM_PICK_UP
   
   # Disable disguised players from getting damaged by mobs (including projectiles and other non-living mobs)
   mob-damage: DISABLE_MOB_DAMAGE
   
   # Disable disguised players from getting targeted by monsters
   mob-target: DISABLE_MOB_TARGET
   
modify:
   
   # Modify players' display names who are disguised as other players
   display-name: MODIFY_DISPLAY_NAME
   
undisguise:
   
   # Undisguise disguised players when they do PvP
   pvp: UNDISGUISE_PVP
   
   # Undisguise disguised players when they do PvE (this means all damage between a player and another mob)
   pve: UNDISGUISE_PVE
   
   # Undisguise disguised players when they are hit by a projectile (e.g. arrow, snowball etc.)
   projectile: UNDISGUISE_PROJECTILE